// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>AmplaTools.ProjectCreate.Messages</NameSpace><Collection>DefinedType</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><CollectionBase>ItemCollection</CollectionBase><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace AmplaTools.ProjectCreate.Messages
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://github.com/AmplaTools/ProjectCreate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate", IsNullable = false)]
    public partial class Hierarchy : System.ComponentModel.INotifyPropertyChanged
    {

        private Enterprise enterpriseField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public Enterprise Enterprise
        {
            get
            {
                return this.enterpriseField;
            }
            set
            {
                if ((this.enterpriseField != null))
                {
                    if ((enterpriseField.Equals(value) != true))
                    {
                        this.enterpriseField = value;
                        this.OnPropertyChanged("Enterprise");
                    }
                }
                else
                {
                    this.enterpriseField = value;
                    this.OnPropertyChanged("Enterprise");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate", IsNullable = true)]
    public partial class Enterprise : System.ComponentModel.INotifyPropertyChanged
    {

        private SiteCollection siteField;

        private string nameField;

        private string idField;

        [System.Xml.Serialization.XmlElementAttribute("Site", Order = 0)]
        public SiteCollection Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                if ((this.siteField != null))
                {
                    if ((siteField.Equals(value) != true))
                    {
                        this.siteField = value;
                        this.OnPropertyChanged("Site");
                    }
                }
                else
                {
                    this.siteField = value;
                    this.OnPropertyChanged("Site");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField != null))
                {
                    if ((idField.Equals(value) != true))
                    {
                        this.idField = value;
                        this.OnPropertyChanged("id");
                    }
                }
                else
                {
                    this.idField = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate", IsNullable = true)]
    public partial class Site : System.ComponentModel.INotifyPropertyChanged
    {

        private AreaCollection areaField;

        private string nameField;

        private string idField;

        [System.Xml.Serialization.XmlElementAttribute("Area", Order = 0)]
        public AreaCollection Area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                if ((this.areaField != null))
                {
                    if ((areaField.Equals(value) != true))
                    {
                        this.areaField = value;
                        this.OnPropertyChanged("Area");
                    }
                }
                else
                {
                    this.areaField = value;
                    this.OnPropertyChanged("Area");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField != null))
                {
                    if ((idField.Equals(value) != true))
                    {
                        this.idField = value;
                        this.OnPropertyChanged("id");
                    }
                }
                else
                {
                    this.idField = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate", IsNullable = true)]
    public partial class Area : System.ComponentModel.INotifyPropertyChanged
    {

        private WorkCentreCollection workCentreField;

        private AreaCollection area1Field;

        private string nameField;

        private string idField;

        [System.Xml.Serialization.XmlElementAttribute("WorkCentre", Order = 0)]
        public WorkCentreCollection WorkCentre
        {
            get
            {
                return this.workCentreField;
            }
            set
            {
                if ((this.workCentreField != null))
                {
                    if ((workCentreField.Equals(value) != true))
                    {
                        this.workCentreField = value;
                        this.OnPropertyChanged("WorkCentre");
                    }
                }
                else
                {
                    this.workCentreField = value;
                    this.OnPropertyChanged("WorkCentre");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Area", Order = 1)]
        public AreaCollection Area1
        {
            get
            {
                return this.area1Field;
            }
            set
            {
                if ((this.area1Field != null))
                {
                    if ((area1Field.Equals(value) != true))
                    {
                        this.area1Field = value;
                        this.OnPropertyChanged("Area1");
                    }
                }
                else
                {
                    this.area1Field = value;
                    this.OnPropertyChanged("Area1");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField != null))
                {
                    if ((idField.Equals(value) != true))
                    {
                        this.idField = value;
                        this.OnPropertyChanged("id");
                    }
                }
                else
                {
                    this.idField = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://github.com/AmplaTools/ProjectCreate", IsNullable = true)]
    public partial class WorkCentre : System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private string idField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                if ((this.idField != null))
                {
                    if ((idField.Equals(value) != true))
                    {
                        this.idField = value;
                        this.OnPropertyChanged("id");
                    }
                }
                else
                {
                    this.idField = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
